const encontros=[
{aba:'junho',data:'2026-06-09T17:00:00-03:00',label:'09/06',titulo:'Aula 1 — Abertura, UNATI, IA e teste dos jogos',resumo:'Conhecer o público da UNATI, entender o papel da IA e testar prompts bons e ruins para gerar jogos simples em HTML.',detalhes:true},
{aba:'junho',data:'2026-06-16T17:00:00-03:00',label:'16/06',titulo:'Aula 2 — Escolha do jogo e desenho das telas',resumo:'Grupos definem o tipo de jogo, público, tema neuroanatômico e desenham as telas iniciais.'},
{aba:'junho',data:'2026-06-23T17:00:00-03:00',label:'23/06',titulo:'Aula 3 — HTML e estrutura do jogo',resumo:'Criação da primeira página do jogo: título, instruções, área do jogo e botões acessíveis.'},
{aba:'junho',data:'2026-06-30T17:00:00-03:00',label:'30/06',titulo:'Aula 4 — CSS, contraste e acessibilidade visual',resumo:'Ajuste de fontes, cores, botões, espaçamento e layout para iPhone, Android e computador.'},
{aba:'julho',data:'2026-07-07T17:00:00-03:00',label:'07/07',titulo:'Aula 5 — JavaScript e lógica do jogo',resumo:'Interação, pontuação, respostas, feedback positivo e comandos simples.'},
{aba:'agosto',data:'2026-08-04T17:00:00-03:00',label:'04/08',titulo:'Aula 6 — Testes simulados com perfil 60+',resumo:'Simulação de uso por pessoa idosa: leitura, toque, compreensão, tempo e segurança emocional.'},
{aba:'agosto',data:'2026-08-11T17:00:00-03:00',label:'11/08',titulo:'Aula 7 — GitHub e organização do projeto',resumo:'Publicação do jogo no GitHub Pages, revisão dos arquivos e organização das equipes.'},
{aba:'agosto',data:'2026-08-18T17:00:00-03:00',label:'18/08',titulo:'Aula 8 — PWA, instalação e ensaio',resumo:'Transformar o jogo em app instalável, testar em celular e preparar apresentação.'},
{aba:'final',data:'2026-08-31T17:00:00-03:00',label:'31/08',titulo:'Aula 9 — Apresentação final conjunta à UNATI',resumo:'Turmas de terça e quarta juntas para apresentação dos jogos à UNATI, com escuta, demonstração e avaliação.'}
];
function abrirAba(id){document.querySelectorAll('.tab').forEach(t=>t.classList.remove('active'));document.querySelectorAll('.tab-content').forEach(c=>c.classList.remove('active'));document.querySelector(`[onclick="abrirAba('${id}')"]`).classList.add('active');document.getElementById(id).classList.add('active')}
function isOpen(d){return new Date()>=new Date(d)}
function diffText(d){let diff=new Date(d)-new Date();if(diff<=0)return'Aula liberada';let days=Math.floor(diff/864e5);diff-=days*864e5;let h=Math.floor(diff/36e5);diff-=h*36e5;let m=Math.floor(diff/6e4);diff-=m*6e4;let s=Math.floor(diff/1e3);return`${days}d ${h}h ${m}min ${s}s`}
function aula1Detalhes(){return `<div class="steps"><div class="step"><b>1. Abertura — 10 min</b><p>Apresentar Medicina + Neuroanatomia + IA + UNATI. Pergunta: “Quem aqui já jogou memória, sudoku, cruzadas, caça-palavras ou bolhas?”</p></div><div class="step"><b>2. Perfil da UNATI — 15 min</b><p>Explicar envelhecimento ativo, inclusão digital e pessoa idosa como sujeito autônomo, ativo e com direitos.</p></div><div class="step"><b>3. O que é chat/IA — 15 min</b><p>Mostrar que ChatGPT, Gemini, Canva e outras IAs ajudam a gerar protótipos, mas precisam de comando claro e revisão humana.</p></div><div class="step"><b>4. Teste dos prompts — 35 min</b><p>Cada dupla usa os dois prompts abaixo e compara o resultado: jogo poluído versus jogo acessível.</p></div><div class="step"><b>5. Simulação 60+ — 25 min</b><p>Testar como se fosse uma pessoa idosa: fonte, contraste, botão, instrução, tempo e medo de errar.</p></div><div class="step"><b>6. Escolha do jogo — 30 min</b><p>Com base na pesquisa da UNATI, cada grupo escolhe o tipo de jogo que desenvolverá nas próximas semanas.</p></div></div><h4>Checklist da Aula 1</h4><div class="checklist"><label><input type="checkbox"> Entendi o que é a UNATI e quem é o público beneficiado.</label><label><input type="checkbox"> Entendi que pessoa idosa não significa incapacidade.</label><label><input type="checkbox"> Testei um prompt ruim e observei os problemas.</label><label><input type="checkbox"> Testei um prompt limpo e comparei o resultado.</label><label><input type="checkbox"> Analisei acessibilidade: fonte, contraste, botões e feedback.</label><label><input type="checkbox"> Escolhi um jogo com meu grupo.</label></div><div class="prompts"><div class="prompt bad"><h4>Prompt 1 — ruim/poluído</h4><pre>Crie um jogo em HTML sobre neuroanatomia para idosos, mas coloque muitas cores, muitas informações na tela, cronômetro rápido, letras pequenas, vários botões, sons e mensagens de erro. Quero ver como fica um exemplo difícil de usar.</pre></div><div class="prompt good"><h4>Prompt 2 — limpo/acessível</h4><pre>Crie um jogo simples em HTML, CSS e JavaScript sobre Neuroanatomia para pessoas idosas da UNATI. Use letras grandes, alto contraste, botões grandes, uma tarefa por vez, instruções curtas, sem cronômetro, feedback positivo e linguagem respeitosa. O jogo deve ensinar memória e atenção de forma fácil.</pre></div></div><h4>Depois do teste</h4><div class="checklist"><label><input type="checkbox"> O que ficou ruim no primeiro jogo?</label><label><input type="checkbox"> O que ficou melhor no segundo jogo?</label><label><input type="checkbox"> O que uma pessoa da UNATI teria dificuldade de usar?</label><label><input type="checkbox"> Qual jogo o grupo vai desenvolver: Quiz, Sudoku, Cartas/Memória, Palavras Cruzadas ou Bolhas?</label></div>`}
function render(){const c={junho:document.getElementById('junho'),julho:document.getElementById('julho'),agosto:document.getElementById('agosto'),final:document.getElementById('final')};Object.values(c).forEach(x=>x.innerHTML='');encontros.forEach((e,i)=>{let aberto=isOpen(e.data);let card=document.createElement('article');card.className='card '+(aberto?'open':'locked');card.innerHTML=`<div class="card-header"><div class="date-badge">${e.label}<br><small>17h</small></div><div style="flex:1"><h3>${e.titulo}</h3><span class="countdown">${aberto?'✅ Aula aberta':'🔒 Abre em: '+diffText(e.data)}</span><p>${e.resumo}</p></div><div class="lock">${aberto?'🟢':'🔒'}</div></div>${aberto&&e.detalhes?aula1Detalhes():''}${!aberto?'<p><b>Conteúdo bloqueado.</b> O roteiro detalhado será liberado no dia e horário do encontro.</p>':''}`;c[e.aba].appendChild(card)});document.getElementById('pdfTable').innerHTML=encontros.map((e,i)=>`<tr><td>${e.label}/2026</td><td>Aula ${i+1}</td><td>${e.titulo} — ${e.resumo}</td></tr>`).join('')}
setInterval(render,1000);render();
function gerarPDF(){let a=document.getElementById('pdfArea');a.style.display='block';html2pdf().set({margin:10,filename:'calendario_neurogames_unati_uem.pdf',image:{type:'jpeg',quality:.98},html2canvas:{scale:2},jsPDF:{unit:'mm',format:'a4',orientation:'portrait'}}).from(a).save().then(()=>a.style.display='none')}
let deferredPrompt;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e});document.getElementById('installBtn').addEventListener('click',async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null}else alert('Para instalar: Android: três pontos > Adicionar à tela inicial. iPhone: Compartilhar > Adicionar à Tela de Início.')});
function toggleChat(){document.getElementById('chatbot').classList.toggle('open')}function responder(t){const r={unati:'A UNATI é a Universidade Aberta à Terceira Idade. Neste projeto, ela é o público beneficiado: pessoas 60+ que participam de aprendizagem, convivência e inclusão.',idosa:'No Brasil, o Estatuto da Pessoa Idosa considera pessoa idosa aquela com 60 anos ou mais. Isso não significa incapacidade: muitas são ativas, conectadas, autônomas e participativas.',respeito:'Valorizar a pessoa idosa é usar linguagem respeitosa, evitar infantilização, reconhecer autonomia, experiência de vida e direito à participação social.',jogos:'Quiz, Sudoku, Cartas/Memória, Palavras Cruzadas e Bolhas trabalham atenção, memória, linguagem, raciocínio e tomada de decisão.',neuro:'A Neuroanatomia entra como conteúdo educativo: memória, atenção, equilíbrio, linguagem, Alzheimer e prevenção de quedas.',ia:'Sim. Os alunos podem usar ChatGPT, Gemini, Canva ou outra IA. A IA ajuda a prototipar, mas o grupo revisa acessibilidade, conteúdo neuroanatômico e respeito ao público 60+.'};let b=document.getElementById('chatBody');b.innerHTML+=`<p class="bot">${r[t]}</p>`;b.scrollTop=b.scrollHeight}
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js'));
